services:
  f3_cinema_db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: f3_cinema_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'f3_cinema'
      MYSQL_USER: 'f3_admin'
      MYSQL_PASSWORD: 'f3_password'
    ports:
      - '3307:3306'
    command: ["--init-file=/docker-entrypoint-initdb.d/init.sql"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    develop:
      watch:
        - action: sync+restart
          path: ./src/main/resources/sql/init.sql
          target: /docker-entrypoint-initdb.d/init.sql

volumes:
  f3_cinema_mysql_data:
    driver: local
